app:
  token:
    secret: testovacka
    expiration: 10
    refresh: 60
  cors:
    origin: "http://localhost:4200"

logging:
  level:
    org.springframework: INFO
    cz.buca: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
   