app:
  admin:
    id: -1
    name: Administrator
    login: admin
    # 12345
    pass: $2a$10$XgfdNZhUxy7EgZxdkWOhF.3/Az.CERogYI2g19AXY1Xj8t80YDoNC
    active: true
    roles:
      - ADMIN
      - USER
  token:
    secret: testovacka
    expiration: 10
    refresh: 60
  cors:
    origin: "http://localhost:4200"

logging:
  level:
    org.springframework: INFO
    cz.buca: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
   